server:
  port: 8002
debug: false #默认false,设置为true，打印debug日志
logging:      #logback-spring.xml 会被这些参数覆盖
  level:
    root: info
    com.amuse.frameone: debug
  path: ./logs
#  file: spring.log #默认是spring.log
#  config: classpath:logback-spring.xml #日志配置文件
security:
  basic:
    enabled: false #关闭spring security basic认证
spring:
  application:
    name: frameone
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 20
      max-idle: 8
      max-wait: 10
      min-idle: 0
    timeout: 10
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: org.apache.tomcat.jdbc.pool.DataSource
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  rabbitmq:
    host: 192.168.32.128
    port: 5672
    username: root
    password: pwd123456
    publisher-confirms: true #消息发送确认
    publisher-returns: true #消息发送失败退回
    listener:
      simple:
        acknowledge-mode: manual #手动ack确认消息
        retry:
          max-attempts: 3
          enabled: true
        concurrency: 1 #一个队列只有一个消费者，保证顺序消费
mybatis:
  config-location: classpath:mybatis-config.xml

#jwt配置
jwt:
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  expiresSecond: 172800
  client-id: 2f81d23110c84862899eb40ace9c9f51
  name: amuseBoy
#mq配置
mq:
  directExchange: directExchange
  directQueue: directQueue
  directRoutingKey: directRoutingKey
  topicExchange: topicExchange
  topicQueue: topic.queue.test
  topicRoutingKey: topic.queue.#
#FTP配置
ftp:
  host: 192.168.32.128
  port: 21
  username: admin
  password: admin
  controlEncoding: utf-8
  connectTimeOut: 5000 #ftp 连接超时时间 毫秒
  bufferSize: 1024 #缓冲区大小
  fileType: 2 #传输数据格式   2表binary二进制数据
  dataTimeout: 120000
  useEPSVwithIPv4: false
  passiveMode: true #是否启用被动模式
  maxTotal: 200
  maxIdle: 20
  minIdle: 10
