server:
  port: 8002
debug: false #默认false,设置为true，打印debug日志
logging:      #logback-spring.xml 会被这些参数覆盖
  level:
    root: info
    com.amuse.frameone: debug
  path: ./logs
#  file: spring.log #默认是spring.log
#  config: classpath:logback-spring.xml #日志配置文件
spring:
  application:
    name: frameone
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
    timeout: 10
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: demo
    password: demo
    type: org.apache.tomcat.jdbc.pool.DataSource
mybatis:
  config-location: classpath:mybatis-config.xml
